name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-22.04

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - name: updage page
        run: |
          cp -rf 0.html ./index.html
          for i in lmi umi cmi
          do
            source device/$i.ini
            sed -i "s/"$i"PKG/$umiPKG/g" ./index.html
            sed -i "s/"$i"MD5/$umiMD5/g" ./index.html
            sed -i "s/"$i"TIME/$umiTIME/g" ./index.html
            sed -i "s/"$i"URL/$umiURL/g" ./index.html
          done
      - name: sync
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          file_pattern: index.html

      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
