name: build
on:
  push:
    branches:    
      - main

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-22.04

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - name: updage page
        run: |
          cp -rf 0.html ./index.html
          chmod 777 $GITHUB_WORKSPACE"/device/*
          source "$GITHUB_WORKSPACE"/device/UMI.ini
          source "$GITHUB_WORKSPACE"/device/CMI.ini
          sed -i "s/UMIPKG/$UMIPKG/g" ./index.html
          sed -i "s/UMIMD5/$UMIMD5/g" ./index.html
          sed -i "s/UMITIME/$UMITIME/g" ./index.html
          sed -i "s/CMIPKG/$CMIPKG/g" ./index.html
          sed -i "s/CMIMD5/$CMIMD5/g" ./index.html
          sed -i "s/CMITIME/$CMITIME/g" ./index.html

      - name: sync
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          file_pattern: index.html
          branch: page

      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
